export const qualifications = [
  'MD',
  'MS',
  'American Board Certified',
  'BAMS',
  'MBBS',
  'MCh',
  'BHMS',
  'BDS',
  'BUMS',
  'DM',
  'LCEH',
  'FRCS',
];

export const specialities = [
  'ENT',
  'General Surgery',
  'Gynaecology',
  'Dermatology',
  'Pediatrics',
  'Pathology',
  'Radiotherapy',
  'Psychiatry',
  'Cardiothoracic Surgery',
  'Orthopaedics',
  'Anaesthesiology',
  'Geriatrics',
  'Pharmacology',
  'Nuclear Medicine',
  'Dentist',
];
